# Generated by Django 3.0.5 on 2020-09-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('CM1', 'large machine'), ('CM0', 'small machine'), ('EM0', 'espresso machine')], max_length=3)),
                ('water_line_compatible', models.BooleanField()),
                ('model', models.PositiveSmallIntegerField(choices=[(1, 'base model'), (2, 'premium model'), (3, 'deluxe model')])),
            ],
        ),
        migrations.CreateModel(
            name='CoffeePod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('CP1', 'large coffee pod'), ('CP0', 'small coffee pod'), ('EM0', 'espresso pod')], max_length=3)),
                ('coffee_flavor', models.PositiveSmallIntegerField(choices=[(0, 'vanilla'), (1, 'caramel'), (3, 'mocha'), (2, 'psl'), (4, 'hazelnut')])),
                ('pack_size', models.PositiveSmallIntegerField(choices=[(1, '1 dozen'), (3, '3 dozen'), (5, '5 dozen'), (7, '7 dozen')])),
            ],
        ),
    ]
